config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :tank_product_compatibilities
  resources :products
  resources :tanks

end

app/models/tank.rb
class Tank < ActiveRecord::Base
  has_many :products, :through => :tank_product_compatibilities

  validates :name, uniqueness: true
  validates :name, :capacity_min, :capacity_max, presence: true
end

app/controllers/tanks_controller.rb
class TanksController < ApplicationController
  before_action :set_tank, only: [:show, :edit, :update, :destroy]

  # GET /tanks
  # GET /tanks.json
  def index
    @tanks = Tank.all
  end

  # GET /tanks/1
  # GET /tanks/1.json
  def show
  end

  # GET /tanks/new
  def new
    @tank = Tank.new
  end

  # GET /tanks/1/edit
  def edit
  end

  # POST /tanks
  # POST /tanks.json
  def create
    @tank = Tank.new(tank_params)

    respond_to do |format|
      if @tank.save
        format.html { redirect_to @tank, notice: 'Tank was successfully created.' }
        format.json { render :show, status: :created, location: @tank }
      else
        format.html { render :new }
        format.json { render json: @tank.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tanks/1
  # PATCH/PUT /tanks/1.json
  def update
    respond_to do |format|
      if @tank.update(tank_params)
        format.html { redirect_to @tank, notice: 'Tank was successfully updated.' }
        format.json { render :show, status: :ok, location: @tank }
      else
        format.html { render :edit }
        format.json { render json: @tank.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tanks/1
  # DELETE /tanks/1.json
  def destroy
    @tank.destroy
    respond_to do |format|
      format.html { redirect_to tanks_url, notice: 'Tank was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tank
      @tank = Tank.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tank_params
      params.require(:tank).permit(:name, :capacity_min, :capacity_max)
    end
end

app/helpers/tanks_helper.rb
module TanksHelper
end

app/views/tanks/_form.html.erb
<%= form_for @tank, :html => { :class => "form-horizontal tank" } do |f| %>

  <% if @tank.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@tank.errors.count, "error") %> prohibited this tank from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @tank.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :capacity_min, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :capacity_min, :class => 'form-control' %>
    </div>
    <%=f.error_span(:capacity_min) %>
  </div>
  <div class="form-group">
    <%= f.label :capacity_max, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :capacity_max, :class => 'form-control' %>
    </div>
    <%=f.error_span(:capacity_max) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                tanks_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/tanks/edit.html.erb
<%- model_class = Tank -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tanks/index.html.erb
<%- model_class = Tank -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:capacity_min) %></th>
      <th><%= model_class.human_attribute_name(:capacity_max) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @tanks.each do |tank| %>
      <tr>
        <td><%= link_to tank.id, tank_path(tank) %></td>
        <td><%= tank.name %></td>
        <td><%= tank.capacity_min %></td>
        <td><%= tank.capacity_max %></td>
        <td><%=l tank.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_tank_path(tank), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      tank_path(tank),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_tank_path,
            :class => 'btn btn-primary' %>

app/views/tanks/new.html.erb
<%- model_class = Tank -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tanks/show.html.erb
<%- model_class = Tank -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @tank.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:capacity_min) %>:</strong></dt>
  <dd><%= @tank.capacity_min %></dd>
  <dt><strong><%= model_class.human_attribute_name(:capacity_max) %>:</strong></dt>
  <dd><%= @tank.capacity_max %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              tanks_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_tank_path(@tank), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              tank_path(@tank),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>