config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :tank_product_compatibilities
  resources :products
  resources :tanks

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :product
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:volume, :expiry, :product_id)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for @order, :html => { :class => "form-horizontal order" } do |f| %>

  <% if @order.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @order.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :volume, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :volume, :class => 'form-control' %>
    </div>
    <%=f.error_span(:volume) %>
  </div>
  <div class="form-group">
    <%= f.label :expiry, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :expiry, :class => 'form-control' %>
    </div>
    <%=f.error_span(:expiry) %>
  </div>
  <div class="form-group">
    <%= f.label :product_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :product_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:product_id) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                orders_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/orders/edit.html.erb
<%- model_class = Order -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/orders/index.html.erb
<%- model_class = Order -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:volume) %></th>
      <th><%= model_class.human_attribute_name(:expiry) %></th>
      <th><%= model_class.human_attribute_name(:product_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= link_to order.id, order_path(order) %></td>
        <td><%= order.volume %></td>
        <td><%= order.expiry %></td>
        <td><%= order.product_id %></td>
        <td><%=l order.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_order_path(order), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      order_path(order),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_order_path,
            :class => 'btn btn-primary' %>

app/views/orders/new.html.erb
<%- model_class = Order -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/orders/show.html.erb
<%- model_class = Order -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:volume) %>:</strong></dt>
  <dd><%= @order.volume %></dd>
  <dt><strong><%= model_class.human_attribute_name(:expiry) %>:</strong></dt>
  <dd><%= @order.expiry %></dd>
  <dt><strong><%= model_class.human_attribute_name(:product_id) %>:</strong></dt>
  <dd><%= @order.product_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              orders_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_order_path(@order), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              order_path(@order),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>