config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :tank_product_compatibilities
  resources :products
  resources :tanks

end

app/models/tank_product_compatibility.rb
class TankProductCompatibility < ActiveRecord::Base
  belongs_to :tank
  belongs_to :product
end

app/controllers/tank_product_compatibilities_controller.rb
class TankProductCompatibilitiesController < ApplicationController
  before_action :set_tank_product_compatibility, only: [:show, :edit, :update, :destroy]

  # GET /tank_product_compatibilities
  # GET /tank_product_compatibilities.json
  def index
    @tank_product_compatibilities = TankProductCompatibility.all
  end

  # GET /tank_product_compatibilities/1
  # GET /tank_product_compatibilities/1.json
  def show
  end

  # GET /tank_product_compatibilities/new
  def new
    @tank_product_compatibility = TankProductCompatibility.new
  end

  # GET /tank_product_compatibilities/1/edit
  def edit
  end

  # POST /tank_product_compatibilities
  # POST /tank_product_compatibilities.json
  def create
    @tank_product_compatibility = TankProductCompatibility.new(tank_product_compatibility_params)

    respond_to do |format|
      if @tank_product_compatibility.save
        format.html { redirect_to @tank_product_compatibility, notice: 'Tank product compatibility was successfully created.' }
        format.json { render :show, status: :created, location: @tank_product_compatibility }
      else
        format.html { render :new }
        format.json { render json: @tank_product_compatibility.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tank_product_compatibilities/1
  # PATCH/PUT /tank_product_compatibilities/1.json
  def update
    respond_to do |format|
      if @tank_product_compatibility.update(tank_product_compatibility_params)
        format.html { redirect_to @tank_product_compatibility, notice: 'Tank product compatibility was successfully updated.' }
        format.json { render :show, status: :ok, location: @tank_product_compatibility }
      else
        format.html { render :edit }
        format.json { render json: @tank_product_compatibility.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tank_product_compatibilities/1
  # DELETE /tank_product_compatibilities/1.json
  def destroy
    @tank_product_compatibility.destroy
    respond_to do |format|
      format.html { redirect_to tank_product_compatibilities_url, notice: 'Tank product compatibility was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tank_product_compatibility
      @tank_product_compatibility = TankProductCompatibility.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tank_product_compatibility_params
      params.require(:tank_product_compatibility).permit(:tank_id, :product_id)
    end
end

app/helpers/tank_product_compatibilities_helper.rb
module TankProductCompatibilitiesHelper
end

app/views/tank_product_compatibilities/_form.html.erb
<%= form_for @tank_product_compatibility, :html => { :class => "form-horizontal tank_product_compatibility" } do |f| %>

  <% if @tank_product_compatibility.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@tank_product_compatibility.errors.count, "error") %> prohibited this tank_product_compatibility from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @tank_product_compatibility.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :tank_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :tank_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:tank_id) %>
  </div>
  <div class="form-group">
    <%= f.label :product_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :product_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:product_id) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                tank_product_compatibilities_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/tank_product_compatibilities/edit.html.erb
<%- model_class = TankProductCompatibility -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tank_product_compatibilities/index.html.erb
<%- model_class = TankProductCompatibility -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:tank_id) %></th>
      <th><%= model_class.human_attribute_name(:product_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @tank_product_compatibilities.each do |tank_product_compatibility| %>
      <tr>
        <td><%= link_to tank_product_compatibility.id, tank_product_compatibility_path(tank_product_compatibility) %></td>
        <td><%= tank_product_compatibility.tank_id %></td>
        <td><%= tank_product_compatibility.product_id %></td>
        <td><%=l tank_product_compatibility.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_tank_product_compatibility_path(tank_product_compatibility), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      tank_product_compatibility_path(tank_product_compatibility),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_tank_product_compatibility_path,
            :class => 'btn btn-primary' %>

app/views/tank_product_compatibilities/new.html.erb
<%- model_class = TankProductCompatibility -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tank_product_compatibilities/show.html.erb
<%- model_class = TankProductCompatibility -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:tank_id) %>:</strong></dt>
  <dd><%= @tank_product_compatibility.tank_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:product_id) %>:</strong></dt>
  <dd><%= @tank_product_compatibility.product_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              tank_product_compatibilities_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_tank_product_compatibility_path(@tank_product_compatibility), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              tank_product_compatibility_path(@tank_product_compatibility),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>